org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m
org.gradle.java.home=/opt/homebrew/opt/openjdk@17
android.useAndroidX=true
android.enableJetifier=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
android.suppressUnsupportedCompileSdk=36
kotlin.jvm.target.validation.mode=warning
